
version: '3.8'
services:
  kekr:
    image: kekr:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./data:/var/lib/postgresql/data
networks:
  app_network:
    driver: bridge
